### ISSUE TITLE
Cannot instantiate the Lut3DParams.Cube

### ISSUE THREAD

**Issue by Vensent** [silvaren/easyrs#4]
When I tried to use the method _Lut3D.apply3dLut_ , I found I cannot instantiate a Lut3DParams.Cube

Anyway, I admit this is a very good tool.

But, please make improvement.

**Comment by silvaren** [comment]
Good catch, thanks for your contribution!

**Comment by rishabhMaltare** [comment]
Similar thing for LutParams.RGBALut(rLut, gLut, bLut, aLut) too. Cannot instantiate it.

**Comment by silvaren** [comment]
@rishabhMaltare also true. I will setup my Android environment to fix and release a new version with the fixes soon after I come back from holidays. Feel free to open a pull request about it if you feel like it :)
